"""
CAM++ Speaker Verification Training Script.
Fine-tunes a pretrained CAM++ on VoxCeleb2 and evaluates on VoxCeleb1-O.

Optimized for low-VRAM GPUs (e.g., RTX 3050 4GB):
  - Batch size 32 (vs 64 for ECAPA on 3090)
  - Mixed-precision training (AMP)
  - Gradient accumulation option
"""

import argparse
import glob
import os
import time
import warnings

import torch

# Add parent dir to path so we can import ECAPATDNN modules
import sys
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))

from campplus.dataloader import train_loader
from ECAPATDNN.tools import init_args
from campplus.CAMPPlusModel import CAMPPlusModel

parser = argparse.ArgumentParser(description="CAM++ Speaker Verification Trainer")

# Training Settings
parser.add_argument('--num_frames', type=int, default=200,
                    help='Duration of input segments. 200 = ~2 seconds')
parser.add_argument('--max_epoch', type=int, default=15,
                    help='Max epochs (fewer needed for fine-tuning)')
parser.add_argument('--batch_size', type=int, default=64,
                    help='Batch size (32 fits in 4GB VRAM)')
parser.add_argument('--n_cpu', type=int, default=8,
                    help='Number of dataloader workers')
parser.add_argument('--test_step', type=int, default=5,
                    help='Evaluate every N epochs')
parser.add_argument('--lr', type=float, default=0.0001,
                    help='Learning rate (lower for fine-tuning)')
parser.add_argument('--lr_decay', type=float, default=0.97,
                    help='LR decay every test_step epochs')

# Paths
parser.add_argument('--train_list', type=str,
                    default='data/campplus/train_list_campplus_wav.txt',
                    help='Training list file (generated by prepare_voxceleb2.py)')
parser.add_argument('--train_path', type=str,
                    default='data/campplus/Voxceleb2_dev_wav/parta',
                    help='Training data directory (with .wav files)')
parser.add_argument('--eval_list', type=str,
                    default='data/campplus/test_list.txt',
                    help='Evaluation trial list')
parser.add_argument('--eval_path', type=str,
                    default='data/campplus/vox1_test_wav/wav',
                    help='Evaluation data directory')
parser.add_argument('--musan_path', type=str,
                    default='data/campplus/musan_split',
                    help='MUSAN augmentation data')
parser.add_argument('--rir_path', type=str,
                    default='data/campplus/RIRS_NOISES/simulated_rirs',
                    help='RIR augmentation data')
parser.add_argument('--save_path', type=str,
                    default='exps/campplus_sv',
                    help='Save path for models and scores')

# Model settings
parser.add_argument('--feat_dim', type=int, default=80,
                    help='Fbank feature dimension')
parser.add_argument('--embedding_size', type=int, default=512,
                    help='Speaker embedding dimension')
parser.add_argument('--m', type=float, default=0.2,
                    help='AAM-Softmax margin')
parser.add_argument('--s', type=float, default=30,
                    help='AAM-Softmax scale')
parser.add_argument('--n_class', type=int, default=0,
                    help='Number of speakers (auto-detected from train_list if 0)')

# Pretrained model
parser.add_argument('--pretrained', type=str, default=None,
                    help='Path to pretrained CAM++ weights (auto-downloads if not set)')

# Commands
parser.add_argument('--eval', dest='eval', action='store_true',
                    help='Only do evaluation')
parser.add_argument('--initial_model', type=str, default='',
                    help='Resume from this checkpoint')

# Gradient accumulation for very low VRAM
parser.add_argument('--grad_accum', type=int, default=1,
                    help='Gradient accumulation steps (effective batch = batch_size * grad_accum)')


def download_pretrained():
    """Download pretrained CAM++ VoxCeleb weights from ModelScope."""
    from campplus.extractor import CAMPPlusExtractor
    return CAMPPlusExtractor.download_pretrained(
        model_id="iic/speech_campplus_sv_en_voxceleb_16k"
    )


if __name__ == "__main__":
    warnings.simplefilter("ignore")
    torch.multiprocessing.set_sharing_strategy('file_system')
    torch.backends.cudnn.benchmark = True

    args = parser.parse_args()
    args = init_args(args)

    # Auto-download pretrained weights if not specified
    pretrained_path = args.pretrained
    if pretrained_path is None and not args.eval and args.initial_model == '':
        print("[INFO] No pretrained path specified. Downloading CAM++ VoxCeleb weights...")
        pretrained_path = download_pretrained()

    # Build data loader (reuses ECAPATDNN data pipeline)
    trainloader = train_loader(**vars(args))
    trainLoader = torch.utils.data.DataLoader(
        trainloader,
        batch_size=args.batch_size,
        shuffle=True,
        num_workers=args.n_cpu,
        drop_last=True,
        pin_memory=True,
    )

    # Count speakers from training list (auto-detect)
    lines = open(args.train_list).read().splitlines()
    n_speakers = len(set([x.split()[0] for x in lines]))
    if args.n_class == 0 or args.n_class != n_speakers:
        print(f"[INFO] Setting n_class = {n_speakers} (from training list)")
        args.n_class = n_speakers

    # Search for existing checkpoints
    modelfiles = glob.glob('%s/model_0*.model' % args.model_save_path)
    modelfiles.sort()

    # Eval-only mode
    if args.eval:
        s = CAMPPlusModel(**vars(args))
        print("Model %s loaded!" % args.initial_model)
        s.load_parameters(args.initial_model)
        EER, minDCF = s.eval_network(eval_list=args.eval_list, eval_path=args.eval_path)
        print("EER %2.2f%%, minDCF %.4f" % (EER, minDCF))
        quit()

    # Load from checkpoint or initial model or pretrained
    if args.initial_model != "":
        print("Model %s loaded from previous state!" % args.initial_model)
        s = CAMPPlusModel(**vars(args))
        s.load_parameters(args.initial_model)
        epoch = 1
    elif len(modelfiles) >= 1:
        print("Model %s loaded from previous state!" % modelfiles[-1])
        epoch = int(os.path.splitext(os.path.basename(modelfiles[-1]))[0][6:]) + 1
        s = CAMPPlusModel(**vars(args))
        s.load_parameters(modelfiles[-1])
    else:
        epoch = 1
        s = CAMPPlusModel(pretrained_path=pretrained_path, **vars(args))

    EERs = []
    score_file = open(args.score_save_path, "a+")

    while True:
        loss, lr, acc = s.train_network(epoch=epoch, loader=trainLoader)

        if epoch % args.test_step == 0:
            s.save_parameters(args.model_save_path + "/model_%04d.model" % epoch)
            EER, minDCF = s.eval_network(
                eval_list=args.eval_list, eval_path=args.eval_path
            )
            EERs.append(EER)
            print(
                time.strftime("%Y-%m-%d %H:%M:%S"),
                "%d epoch, ACC %2.2f%%, EER %2.2f%%, bestEER %2.2f%%"
                % (epoch, acc, EERs[-1], min(EERs)),
            )
            score_file.write(
                "%d epoch, LR %f, LOSS %f, ACC %2.2f%%, EER %2.2f%%, bestEER %2.2f%%\n"
                % (epoch, lr, loss, acc, EERs[-1], min(EERs))
            )
            score_file.flush()

        if epoch >= args.max_epoch:
            quit()

        epoch += 1
